context:
  name: essdiffraction
  version: "25.10.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essdiffraction-${{ version }}.tar.gz
  sha256: 78a30c5f0e1d6f08e7a3a1dad9ba0874ad1fadf6fb3db652ddf17e81e8a2af98

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - essreduce >=25.10.1
    - python-graphviz
    - numpy >=1.25
    - plopp >=25.07.0
    - pythreejs >=2.4.1
    - sciline >=25.04.1
    - scipp >=25.05.1
    - scippneutron >=25.02.0
    - scippnexus >=23.12.0
    - tof >=25.01.2

tests:
  - python:
      imports:
        - ess.diffraction
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Diffraction data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essdiffraction
  homepage: https://scipp.github.io/essdiffraction/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
