context:
  name: essdiffraction
  version: "25.8.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essdiffraction-${{ version }}.tar.gz
  sha256: 6473865db915eadda02ded8fbc002b7d4a93f41d502330080f089f3378d9c613

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core
    - essreduce >=25.05.3
    - python-graphviz
    - numpy
    - plopp >=25.03.0
    - pythreejs
    - sciline >=25.04.1
    - scipp >=25.05.1
    - scippneutron >=25.02.0
    - scippnexus >=23.12.0
    - tof >=25.01.2

tests:
  - python:
      imports:
        - ess.diffraction
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Diffraction data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essdiffraction
  homepage: https://scipp.github.io/essdiffraction/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
